const CATEGORIES = [
	{
		id: 1,
		name: "Rose",
		colors: ["Red,", "Pink,", "White"],
		festivals: ["Valentine's Day", "Wedding"],
		theme: "Romantic",
		cost: 25,
		categoryType: "Cut Flower",
		decoration: "Bouquets, centerpieces",
		useIn: ["home", "wedding", "school"],
		ceremony: ["Wedding", "Anniversary"],
		rating: 4.8,
		reviews: 342,
		owner: { name: "Asha Flowers", phone: "+1-555-0101", email: "asha@flora.com" }
	},
	{
		id: 2,
		name: "Marigold",
		colors: ["Orange", "Yellow"],
		festivals: ["Diwali", "Navratri"],
		theme: "Traditional",
		cost: 8,
		categoryType: "Garland Flower",
		decoration: "Garlands, rangoli edges",
		useIn: ["home", "temple", "festival"],
		ceremony: ["Puja", "Procession"],
		rating: 4.5,
		reviews: 210,
		owner: { name: "Suresh Nurseries", phone: "+1-555-0102", email: "contact@sureshnursery.com" }
	},
	{
		id: 3,
		name: "Jasmine",
		colors: ["White"],
		festivals: ["Wedding", "Religious"],
		theme: "Fragrant",
		cost: 15,
		categoryType: "Aromatic Flower",
		decoration: "Garlands, hair adornment",
		useIn: ["home", "temple", "wedding"],
		ceremony: ["Wedding", "Puja"],
		rating: 4.7,
		reviews: 178,
		owner: { name: "GreenAura", phone: "+1-555-0103", email: "hello@greenaura.com" }
	},
	{
		id: 4,
		name: "Lotus",
		colors: ["Pink", "White"],
		festivals: ["Religious"],
		theme: "Sacred",
		cost: 30,
		categoryType: "Aquatic Flower",
		decoration: "Temple offerings, centerpieces",
		useIn: ["temple", "festival"],
		ceremony: ["Puja"],
		rating: 4.9,
		reviews: 420,
		owner: { name: "Lotus Grove", phone: "+1-555-0104", email: "sales@lotusgrove.com" }
	},
	{
		id: 5,
		name: "Lily",
		colors: ["White", "Orange", "Pink"],
		festivals: ["Easter", "Funeral"],
		theme: "Elegant",
		cost: 22,
		categoryType: "Cut Flower",
		decoration: "Vases, wreaths",
		useIn: ["home", "ceremony"],
		ceremony: ["Funeral", "Wedding"],
		rating: 4.6,
		reviews: 156,
		owner: { name: "BloomVista", phone: "+1-555-0105", email: "info@bloomvista.com" }
	},
	{
		id: 6,
		name: "Tulip",
		colors: ["Red", "Yellow", "Purple"],
		festivals: ["Spring Festival"],
		theme: "Spring",
		cost: 12,
		categoryType: "Bulb Flower",
		decoration: "Bouquets, borders",
		useIn: ["home", "school"],
		ceremony: ["Spring Fair"],
		rating: 4.4,
		reviews: 98,
		owner: { name: "Holland Picks", phone: "+1-555-0106", email: "orders@hollandpicks.com" }
	},
	{
		id: 7,
		name: "Hibiscus",
		colors: ["Red", "Pink", "Yellow"],
		festivals: ["Cultural"],
		theme: "Tropical",
		cost: 9,
		categoryType: "Shrub Flower",
		decoration: "Garlands, outdoor decor",
		useIn: ["home", "festival"],
		ceremony: ["Cultural Events"],
		rating: 4.2,
		reviews: 64,
		owner: { name: "Island Greens", phone: "+1-555-0107", email: "contact@islandgreens.com" }
	},
	{
		id: 8,
		name: "Sunflower",
		colors: ["Yellow"],
		festivals: ["Harvest Festival"],
		theme: "Cheerful",
		cost: 10,
		categoryType: "Field Flower",
		decoration: "Bouquets, outdoor displays",
		useIn: ["home", "festival"],
		ceremony: ["Harvest"],
		rating: 4.6,
		reviews: 201,
		owner: { name: "SunnyPatch", phone: "+1-555-0108", email: "sales@sunnypatch.com" }
	},
	{
		id: 9,
		name: "Orchid",
		colors: ["Purple", "White", "Pink"],
		festivals: ["Anniversary", "Corporate"],
		theme: "Exotic",
		cost: 45,
		categoryType: "Potted Flower",
		decoration: "Table centerpieces, gifts",
		useIn: ["home", "office"],
		ceremony: ["Anniversary", "Reception"],
		rating: 4.9,
		reviews: 512,
		owner: { name: "Orchid House", phone: "+1-555-0109", email: "care@orchidhouse.com" }
	},
	{
		id: 10,
		name: "Chrysanthemum",
		colors: ["White", "Yellow", "Red"],
		festivals: ["Autumn Festival"],
		theme: "Classic",
		cost: 14,
		categoryType: "Cut Flower",
		decoration: "Wreaths, vases",
		useIn: ["home", "ceremony"],
		ceremony: ["Memorial"],
		rating: 4.3,
		reviews: 134,
		owner: { name: "PetalCraft", phone: "+1-555-0110", email: "orders@petalcraft.com" }
	},
	{
		id: 11,
		name: "Daffodil",
		colors: ["Yellow"],
		festivals: ["Spring"],
		theme: "Fresh",
		cost: 9,
		categoryType: "Bulb Flower",
		decoration: "Garden beds, bouquets",
		useIn: ["home", "school"],
		ceremony: ["Spring Events"],
		rating: 4.1,
		reviews: 58,
		owner: { name: "Meadow Roots", phone: "+1-555-0111", email: "info@meadowroots.com" }
	},
	{
		id: 12,
		name: "Carnation",
		colors: ["Pink", "Red", "White"],
		festivals: ["Mother's Day"],
		theme: "Versatile",
		cost: 7,
		categoryType: "Cut Flower",
		decoration: "Corsages, bouquets",
		useIn: ["home", "school", "wedding"],
		ceremony: ["Graduation", "Wedding"],
		rating: 4.0,
		reviews: 74,
		owner: { name: "Classic Blooms", phone: "+1-555-0112", email: "hello@classicblooms.com" }
	},
	{
		id: 13,
		name: "Peony",
		colors: ["Pink", "White", "Red"],
		festivals: ["Wedding"],
		theme: "Luxurious",
		cost: 35,
		categoryType: "Cut Flower",
		decoration: "Bouquets, centerpieces",
		useIn: ["wedding", "home"],
		ceremony: ["Wedding"],
		rating: 4.8,
		reviews: 276,
		owner: { name: "Peony Lane", phone: "+1-555-0113", email: "sales@peonylane.com" }
	},
	{
		id: 14,
		name: "Gardenia",
		colors: ["White"],
		festivals: ["Wedding"],
		theme: "Fragrant",
		cost: 28,
		categoryType: "Shrub Flower",
		decoration: "Boutonnieres, pots",
		useIn: ["home", "wedding"],
		ceremony: ["Wedding", "Reception"],
		rating: 4.6,
		reviews: 142,
		owner: { name: "Fragrant Fields", phone: "+1-555-0114", email: "contact@fragrantfields.com" }
	},
	{
		id: 15,
		name: "Freesia",
		colors: ["Purple", "Yellow", "White"],
		festivals: ["Spring"],
		theme: "Delicate",
		cost: 11,
		categoryType: "Cut Flower",
		decoration: "Bouquets, small arrangements",
		useIn: ["home", "wedding"],
		ceremony: ["Bridal Shower"],
		rating: 4.4,
		reviews: 88,
		owner: { name: "Petal & Stem", phone: "+1-555-0115", email: "orders@petalandstem.com" }
	},
	{
		id: 16,
		name: "Azalea",
		colors: ["Pink", "White"],
		festivals: ["Garden Festival"],
		theme: "Ornamental",
		cost: 20,
		categoryType: "Shrub",
		decoration: "Garden, patio",
		useIn: ["home", "school"],
		ceremony: ["Garden Shows"],
		rating: 4.2,
		reviews: 66,
		owner: { name: "Bloom Gardens", phone: "+1-555-0116", email: "support@bloomgardens.com" }
	},
	{
		id: 17,
		name: "Begonia",
		colors: ["Pink", "Red", "White"],
		festivals: ["Housewarming"],
		theme: "Indoor",
		cost: 13,
		categoryType: "Potted Plant",
		decoration: "Indoor pots, hanging baskets",
		useIn: ["home", "office"],
		ceremony: ["Housewarming"],
		rating: 4.0,
		reviews: 47,
		owner: { name: "Urban Plants", phone: "+1-555-0117", email: "hello@urbanplants.com" }
	},
	{
		id: 18,
		name: "Magnolia",
		colors: ["White", "Pink"],
		festivals: ["Spring"],
		theme: "Statement",
		cost: 40,
		categoryType: "Tree Flower",
		decoration: "Large displays, gardens",
		useIn: ["home", "festival"],
		ceremony: ["Weddings"],
		rating: 4.7,
		reviews: 190,
		owner: { name: "TreeLine", phone: "+1-555-0118", email: "info@treeline.com" }
	},
	{
		id: 19,
		name: "Zinnia",
		colors: ["Pink", "Orange", "Red"],
		festivals: ["Summer Fairs"],
		theme: "Bright",
		cost: 6,
		categoryType: "Annual",
		decoration: "Borders, bouquets",
		useIn: ["home", "school"],
		ceremony: ["Community Events"],
		rating: 4.1,
		reviews: 39,
		owner: { name: "ColorBurst", phone: "+1-555-0119", email: "sales@colorburst.com" }
	},
	{
		id: 20,
		name: "Gerbera",
		colors: ["Pink", "Yellow", "White"],
		festivals: ["Birthday"],
		theme: "Playful",
		cost: 16,
		categoryType: "Cut Flower",
		decoration: "Bouquets, centerpieces",
		useIn: ["home", "party"],
		ceremony: ["Birthday"],
		rating: 4.5,
		reviews: 128,
		owner: { name: "FreshFold", phone: "+1-555-0120", email: "orders@freshfold.com" }
	},
	{
		id: 21,
		name: "Lavender",
		colors: ["Purple"],
		festivals: ["Relaxation Events"],
		theme: "Calming",
		cost: 18,
		categoryType: "Herb/Flower",
		decoration: "Dried bundles, sachets",
		useIn: ["home", "spa"],
		ceremony: ["Wellness"],
		rating: 4.8,
		reviews: 254,
		owner: { name: "Aroma Fields", phone: "+1-555-0121", email: "contact@aromafields.com" }
	},
	{
		id: 22,
		name: "Hyacinth",
		colors: ["Blue", "Purple", "Pink"],
		festivals: ["Spring"],
		theme: "Fragrant",
		cost: 14,
		categoryType: "Bulb Flower",
		decoration: "Indoor pots, bouquets",
		useIn: ["home", "school"],
		ceremony: ["Spring Shows"],
		rating: 4.3,
		reviews: 75,
		owner: { name: "Bulb Boutique", phone: "+1-555-0122", email: "info@bulbboutique.com" }
	},
	{
		id: 23,
		name: "Camellia",
		colors: ["Pink", "White"],
		festivals: ["Cultural"],
		theme: "Classic",
		cost: 26,
		categoryType: "Shrub Flower",
		decoration: "Garden displays, pots",
		useIn: ["home", "festival"],
		ceremony: ["Cultural Events"],
		rating: 4.4,
		reviews: 86,
		owner: { name: "Gardenia Co.", phone: "+1-555-0123", email: "sales@gardeniaco.com" }
	},
	{
		id: 24,
		name: "Poppy",
		colors: ["Red", "Orange"],
		festivals: ["Remembrance"],
		theme: "Remembrance",
		cost: 5,
		categoryType: "Field Flower",
		decoration: "Wreaths, memorials",
		useIn: ["ceremony", "festival"],
		ceremony: ["Memorial"],
		rating: 4.0,
		reviews: 32,
		owner: { name: "Remembrance Florals", phone: "+1-555-0124", email: "info@remembranceflorals.com" }
	},
	{
		id: 25,
		name: "Iris",
		colors: ["Blue", "Purple", "White"],
		festivals: ["Spring"],
		theme: "Artistic",
		cost: 12,
		categoryType: "Perennial",
		decoration: "Bouquets, borders",
		useIn: ["home", "gallery"],
		ceremony: ["Art Events"],
		rating: 4.2,
		reviews: 59,
		owner: { name: "Petal Palette", phone: "+1-555-0125", email: "hello@petalpalette.com" }
	},
	{
		id: 26,
		name: "Snapdragon",
		colors: ["Yellow", "Pink", "White"],
		festivals: ["Garden Shows"],
		theme: "Playful",
		cost: 7,
		categoryType: "Annual",
		decoration: "Borders, bouquet fillers",
		useIn: ["home", "school"],
		ceremony: ["Local Fairs"],
		rating: 4.1,
		reviews: 41,
		owner: { name: "FieldWorks", phone: "+1-555-0126", email: "contact@fieldworks.com" }
	},
	{
		id: 27,
		name: "Ranunculus",
		colors: ["Pink", "Orange", "White"],
		festivals: ["Wedding"],
		theme: "Layered",
		cost: 20,
		categoryType: "Cut Flower",
		decoration: "Bouquets, boutonnières",
		useIn: ["wedding", "home"],
		ceremony: ["Wedding"],
		rating: 4.6,
		reviews: 115,
		owner: { name: "Petal Studio", phone: "+1-555-0127", email: "studio@petalstudio.com" }
	},
	{
		id: 28,
		name: "Stephanotis",
		colors: ["White"],
		festivals: ["Wedding"],
		theme: "Traditional",
		cost: 24,
		categoryType: "Vine Flower",
		decoration: "Bridal bouquets, garlands",
		useIn: ["wedding"],
		ceremony: ["Wedding"],
		rating: 4.5,
		reviews: 67,
		owner: { name: "Bridal Blooms", phone: "+1-555-0128", email: "bridal@blooms.com" }
	},
	{
		id: 29,
		name: "Anemone",
		colors: ["White", "Purple", "Blue"],
		festivals: ["Artisan Markets"],
		theme: "Delicate",
		cost: 17,
		categoryType: "Cut Flower",
		decoration: "Boutonnieres, small bouquets",
		useIn: ["home", "wedding"],
		ceremony: ["Gallery Openings"],
		rating: 4.4,
		reviews: 53,
		owner: { name: "Fine Stems", phone: "+1-555-0129", email: "orders@finestems.com" }
	},
	{
		id: 30,
		name: "Amaranth",
		colors: ["Red", "Burgundy"],
		festivals: ["Harvest"],
		theme: "Rustic",
		cost: 9,
		categoryType: "Dried/Decorative",
		decoration: "Dried arrangements, rustic decor",
		useIn: ["home", "festival"],
		ceremony: ["Autumn Events"],
		rating: 4.0,
		reviews: 29,
		owner: { name: "Rustic Roots", phone: "+1-555-0130", email: "rustic@roots.com" }
	},
	{
		id: 31,
		name: "Sweet Pea",
		colors: ["Pink", "Purple", "White"],
		festivals: ["Spring"],
		theme: "Fragrant",
		cost: 10,
		categoryType: "Climbing Flower",
		decoration: "Cottage gardens, bouquets",
		useIn: ["home", "garden"],
		ceremony: ["Bridal Showers"],
		rating: 4.3,
		reviews: 44,
		owner: { name: "Cottage Flora", phone: "+1-555-0131", email: "hello@cottageflora.com" }
	},
	{
		id: 32,
		name: "Bird of Paradise",
		colors: ["Orange", "Blue"],
		festivals: ["Exotic Shows"],
		theme: "Tropical",
		cost: 55,
		categoryType: "Exotic",
		decoration: "Statement arrangements",
		useIn: ["home", "corporate"],
		ceremony: ["Corporate Events"],
		rating: 4.7,
		reviews: 91,
		owner: { name: "Exotia", phone: "+1-555-0132", email: "info@exotia.com" }
	},
	{
		id: 33,
		name: "Protea",
		colors: ["Pink", "Cream"],
		festivals: ["Designer Weddings"],
		theme: "Bold",
		cost: 60,
		categoryType: "Exotic Cut Flower",
		decoration: "Modern bouquets, displays",
		useIn: ["wedding", "corporate"],
		ceremony: ["Designer Weddings"],
		rating: 4.9,
		reviews: 110,
		owner: { name: "Modern Flora", phone: "+1-555-0133", email: "sales@modernflora.com" }
	},
	{
		id: 34,
		name: "Calla Lily",
		colors: ["White", "Purple"],
		festivals: ["Wedding"],
		theme: "Minimalist",
		cost: 27,
		categoryType: "Cut Flower",
		decoration: "Elegant bouquets, vases",
		useIn: ["wedding", "funeral"],
		ceremony: ["Wedding", "Memorial"],
		rating: 4.6,
		reviews: 133,
		owner: { name: "Elegance Co.", phone: "+1-555-0134", email: "contact@eleganceco.com" }
	},
	{
		id: 35,
		name: "Primrose",
		colors: ["Yellow", "Pink"],
		festivals: ["Spring"],
		theme: "Cottage",
		cost: 6,
		categoryType: "Perennial",
		decoration: "Window boxes, small pots",
		useIn: ["home", "school"],
		ceremony: ["Garden Fairs"],
		rating: 4.0,
		reviews: 21,
		owner: { name: "GreenThumb", phone: "+1-555-0135", email: "support@greenthumb.com" }
	},
	{
		id: 36,
		name: "Verbena",
		colors: ["Purple", "Pink"],
		festivals: ["Summer"],
		theme: "Cascading",
		cost: 5,
		categoryType: "Groundcover",
		decoration: "Hanging baskets, borders",
		useIn: ["home", "festival"],
		ceremony: ["Street Fairs"],
		rating: 4.1,
		reviews: 27,
		owner: { name: "Trailing Blooms", phone: "+1-555-0136", email: "orders@trailingblooms.com" }
	},
	{
		id: 37,
		name: "Salvia",
		colors: ["Purple", "Blue"],
		festivals: ["Garden Shows"],
		theme: "Pollinator Friendly",
		cost: 8,
		categoryType: "Perennial",
		decoration: "Garden beds, pollinator plots",
		useIn: ["home", "school"],
		ceremony: ["Community Gardens"],
		rating: 4.3,
		reviews: 34,
		owner: { name: "Pollinator Patch", phone: "+1-555-0137", email: "hello@pollinatorpatch.com" }
	},
	{
		id: 38,
		name: "Echinacea",
		colors: ["Pink", "Purple"],
		festivals: ["Health & Wellness"],
		theme: "Medicinal",
		cost: 12,
		categoryType: "Herb/Flower",
		decoration: "Garden, dried remedies",
		useIn: ["home", "health"],
		ceremony: ["Wellness Workshops"],
		rating: 4.5,
		reviews: 72,
		owner: { name: "Herb Haven", phone: "+1-555-0138", email: "info@herbhaven.com" }
	},
	{
		id: 39,
		name: "Cosmos",
		colors: ["Pink", "White", "Magenta"],
		festivals: ["Autumn"],
		theme: "Wildflower",
		cost: 4,
		categoryType: "Annual",
		decoration: "Meadows, bouquets",
		useIn: ["home", "festival"],
		ceremony: ["Local Festivals"],
		rating: 4.0,
		reviews: 19,
		owner: { name: "MeadowMix", phone: "+1-555-0139", email: "sales@meadowmix.com" }
	},
	{
		id: 40,
		name: "Fuchsia",
		colors: ["Pink", "Purple"],
		festivals: ["Garden Shows"],
		theme: "Hanging",
		cost: 14,
		categoryType: "Hanging Plant",
		decoration: "Hanging baskets, porch decor",
		useIn: ["home", "festival"],
		ceremony: ["Garden Exhibits"],
		rating: 4.2,
		reviews: 36,
		owner: { name: "Hanging Haven", phone: "+1-555-0140", email: "contact@hanginghaven.com" }
	}
];

export { CATEGORIES };